### ISSUE TITLE
Clean DataSet

### ISSUE THREAD

**Issue by GovardhanNM** [TrailExplorer/preparations#1]
Clean the dataset, Remove any duplicate data, Make the dataset migration ready. Upload before and after dataset with code to the repository

**Comment by lalithkaamala** [comment]
https://colab.research.google.com/drive/1NYvByD8Lk3wVg5-LqLtnAInYG3XagvF8?usp=sharing

**Comment by lalithkaamala** [comment]
Not able to upload ipynb file so uploading a pdf format for the above link notebook.

[BDA_Project.pdf](https://github.com/TrailExplorer/preparations/files/14576054/BDA_Project.pdf)
