### ISSUE TITLE
API’s for Photos and Description

### ISSUE THREAD

**Issue by GovardhanNM** [TrailExplorer/preparations#2]
Find any available API's for photos and Descriptions for Trail.

**Comment by sachi097** [comment]
Found few apis
- https://prescriptiontrails.org/api/
- https://www.hikingproject.com/data

But the second api is discontinued for general public need to find a way to access it either by registering or reaching out to the org.

**Comment by KaranBantia** [comment]
# isntall the library
# pip install googlemaps
# pip install Pillow

import googlemaps
from PIL import Image
import json

API_KEY = 'get your own key'

gmaps = googlemaps.Client(key = API_KEY)

def place_search():
    # Do a simple nearby search where we specify the location
    # in lat/lon format, along with a radius measured in meters
    places_result  = gmaps.places_nearby(location='38.38925, -109.86797', radius = 1000)
    place = places_result['results'][0]
    
    i = 0
   
    my_place_id = place['place_id']
    # define the fields you would liked return. Formatted as a list.
    #print(json.dumps(place))
    my_fields = ['name','formatted_phone_number', 'photo', 'editorial_summary']

    # make a request for the details using the Places API.
    places_details  = gmaps.place(place_id = my_place_id , fields= my_fields)
    # print get the photo id for each photo for each place, returned as a dictionary.
    #print(json.dumps(places_details) )
    for photo in places_details['result']['photos']:
        # define parameters of our photo request.
        photo_id = photo['photo_reference']
        photo_width = 400                      
        photo_height = 400

        # request the image, using the Places Photot API.
        raw_image_data = gmaps.places_photo(photo_reference = photo_id, max_width = photo_width, max_height = photo_height)
        #print(raw_image_data)
        # raw image data is returned so we will save that raw data to a JPG file.
        f = open('MyDownloadedImage.jpg', 'wb')
    
        # save the raw image data to the file in chunks.
        for chunk in raw_image_data:
            if chunk:
                f.write(chunk)
        f.close()

        # we will open the newly saved photo, to display the photo.
        im = Image.open('MyDownloadedImage.jpg')
        im.show()

place_search()

**Comment by KaranBantia** [comment]
Sample response from google api
{
  "html_attributions": [],
  "result": {
    "editorial_summary": {
      "language": "en",
      "overview": "0.5-mi. trail to Mesa Arch, Canyonlands' most famous natural feature & a popular sunrise photo op."
    },
    "formatted_phone_number": "(435) 719-2135",
    "name": "Mesa Arch Trailhead",
    "photos": [
      {
        "height": 3266,
        "html_attributions": [
          "<a href=\"https://maps.google.com/maps/contrib/101412336776779001890\">Chad Colson</a>"
        ],
        "photo_reference": "ATplDJbz1s6kzDdXNj_NrYqn-wZjW1bc_Fdfaq4WErMO1CBRaxRByd8rUSF3j86b5zhLvtttvJ8gqOxk4nx7LAUIageaJ3B6LtAJA52nSZ5m6-7H5vi6SRl3z6LMSplpiCQy9Wx1Mye6UUu_fK9m0VsG5K9l__cIKRMqHfsAuAQJSsW04V8q",
        "width": 4897
      },
      {
        "height": 2933,
        "html_attributions": [
          "<a href=\"https://maps.google.com/maps/contrib/116277927734603801829\">David Bear</a>"
        ],
        "photo_reference": "ATplDJZUPDRhGXO8ltSs7soJX6XfLcOmKydkSBwVJiBq5redvS2o0QeAkN_oj1ZUc74ZpQsYfGUTronQKgj9DT-mKzUGO_2Thr1fLGVMA4wfYs9pH9DtJ71SNzb0_uP1iZAsmBukJYcU2qMq8495JBj5Tp-TpbCLLnmyxfwU6s6M-H06Wl6M",
        "width": 2927
      },
      {
        "height": 3168,
        "html_attributions": [
          "<a href=\"https://maps.google.com/maps/contrib/110997235748299794548\">Steve Porter</a>"
        ],
        "photo_reference": "ATplDJZ1AkJvEfnzXVzOgkHSSyDzr8zJ1EJid8ux_LFy8qYmLsmuLmhnnEHiyWsa4s_zFJfQ2JTSnbvjKMO0q4Ay7YWxwYKKJbb_sK_4KWK2qP3l72a0FM912eoq7AI9K3_tIDTNPyBUHvM2HuYyeKwL5eQrgi-ukml4lN0wdLPkvD0B5CV-",
        "width": 4752
      },
      {
        "height": 3024,
        "html_attributions": [
          "<a href=\"https://maps.google.com/maps/contrib/112734089631156877776\">Alyson Singer</a>"
        ],
        "photo_reference": "ATplDJZ3cmBlFIFVvOaK8zg9cqLsVXd4Huv8Q-xFyIRdPPJ6uG_lnRXKu8HDXUMf1P7mwH4SeO6B47u2sXwIN9bZt4DptuwMTT49sAx6dYp3o2dM8laNz-KU0rXncaSFd5trnJJu47bfh9GSPjPuK1sHIEtK90UjtL29c8eI7-tJxIUDTt14",
        "width": 4032
      },
      {
        "height": 4032,
        "html_attributions": [
          "<a href=\"https://maps.google.com/maps/contrib/114370203841263429855\">Inuk</a>"
        ],
        "photo_reference": "ATplDJZsXj4ngJ0buwJRVShK4TRBnlK20RsSYvO0Jp6I_b3JkDeuE3zFPJnjNjTyYPakFFXsVQwg13X2Rk8pENuNNLSVGj_L3_xzIJlMZDHJMWtJYKYtM6cDdk-ciAnZar72eIGZoVZYPz0TOikOKn0Jrai-K2ClzwWrRZOnNSF1kI8EArPg",
        "width": 3024
      },
      {
        "height": 1868,
        "html_attributions": [
          "<a href=\"https://maps.google.com/maps/contrib/110647413338512827047\">Sanjeev Jahagirdar</a>"
        ],
        "photo_reference": "ATplDJbD_A2sAvA0JAfTcqxHdLT8kWNvNm5IIiJUj2RgQN0tQIthLopW3FD7VnTuuFIYYsmie908Fr2QeXCgCip-AAJY86OQOyrWTHoJUGzP5Cy0KXugpfiBp7EyH8UE0i9kRLK3Yq-3DH1VK5k5164pUgjbyyYpNT_L22ryO5Epov8HGqfk",
        "width": 4000
      },
      {
        "height": 4032,
        "html_attributions": [
          "<a href=\"https://maps.google.com/maps/contrib/102774014695846830055\">Carolyn Sopczak</a>"
        ],
        "photo_reference": "ATplDJaulJWyDFRxiidCstbhuzZfa6UUQqAobnk-sdw9NVmg_yCbQUmpLB5dToqL41cg826lX6zxhUYB64wl3nuKve0BswYBMnBIZMFl6qBdbxqssdyeiewBQs_STpLlSMEfoiL8sZOosc1ddpARWLcsHj4dGjKExwslpkDo_z_gU5HOmYTd",
        "width": 2268
      },
      {
        "height": 3264,
        "html_attributions": [
          "<a href=\"https://maps.google.com/maps/contrib/115017855260204082731\">Andrew S.</a>"
        ],
        "photo_reference": "ATplDJajbzDvQBioc0hbU35mW5_mzPdH_lOL1TuHJj-_U2hkGbFNKSCgf93w4CnAU8_YFtvrK20ETKuEuLuZYzf6ouph8wety96cf6aGUZfti6Kdj0QPwvKcm5qCZfsG0Tbz8keuugm8dEttJpmkvJtYS8ccPNp3cr2Uxnxz_YSuB4BefTZr",
        "width": 4928
      },
      {
        "height": 3265,
        "html_attributions": [
          "<a href=\"https://maps.google.com/maps/contrib/107887921073613377353\">Haley Smith</a>"
        ],
        "photo_reference": "ATplDJZKhSM_Nfzk9962geiC7A3cdmHtG-YLwhBwnLss0M-UT8HHc4YiSrd8G2G9nRaOaOMlfylB97R2WK1uzIPqu9ykL3duWTT3dMXrV1ztEuUoZiNERMeJ1TrPIulhnDp3sEWxNc7H9ZzMgnKlUAsH9pCernRPfXME1n3b5Cp4II6BYPzX",
        "width": 4898
      },
      {
        "height": 3456,
        "html_attributions": [
          "<a href=\"https://maps.google.com/maps/contrib/101847849252064268512\">Cathy Parker</a>"
        ],
        "photo_reference": "ATplDJb5tyfYP1km5G2fQ0tOK_eo9-FY5QJSWMn3g3zKzAsD9r977vFCss_jWOZEzZRdC2GvPadD4l7xf6GHzam_IkQp1EX4GysM-Fd55TGpN9i8XJ6tnPaM9SdTwidfccTEyxhPsMFL_dg33PWBGsa9UdoxRjRgg_3s08P92JZDE2Bm7Edt",
        "width": 4608
      }
    ]
  },
  "status": "OK"
}

**Comment by sachi097** [comment]
Closing this task as code shared by @KaranBantia will be used to fetch images for each trails.

**Comment by sachi097** [comment]
Closing this task as code shared by @KaranBantia will be used to fetch images for each trails.
