### ISSUE TITLE
Compare Cloud platforms

### ISSUE THREAD

**Issue by GovardhanNM** [TrailExplorer/preparations#4]
Compare different Cloud Platforms and see the credits given by them for Student Access. Search for Databases, Containarization methods and CI/CD for these platforms

**Comment by Anirudhpk2001** [comment]
Most famous cloud platforms GCP , AWS and Azure, GCP gives 300$ as a bonus Credits whereas in AWS we AWS free tier ,
coming to Azure it gives 200 $ credits for first users.

I have included a link for AWS.

https://aws.amazon.com/free/?trk=78b916d7-7c94-4cab-98d9-0ce5e648dd5f&sc_channel=ps&ef_id=CjwKCAiA6KWvBhAREiwAFPZM7nIAx_b7Q4S1nhPryMseb7MKdr33NhMi1472LBc59JTBFpkfh3E1WRoCVK4QAvD_BwE:G:s&s_kwcid=AL!4422!3!438195700988!p!!g!!aws%20free%20tier!9572385111!105369897961&all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=tier%2312monthsfree&awsf.Free%20Tier%20Categories=*all

Personally Using AWS will help us learn and with that i think AWS has more resources that can help us with this project.

**Comment by Anirudhpk2001** [comment]
In AWS we have these following required resources:
1.ECS available for free for 6 months (2200 hours/month) ,
2.EC2 available for 12 months for free (750 hours/month),
3. DynamoDB 25 GB for 12 months,
4. lambda 1 Million free requests per month,
5. S3 5GB data , but depending on the dataset we might need to change Platform,

**Comment by sachi097** [comment]
Closing this task @Anirudhpk2001 .

**AWS** will used as a cloud platform for this project.
