### ISSUE TITLE
Database migration

### ISSUE THREAD

**Issue by GovardhanNM** [TrailExplorer/preparations#7]
Migrate CSV to DynamoDB

**Comment by lalithkaamala** [comment]
[Final_Alltrails.csv](https://github.com/TrailExplorer/preparations/files/14575878/Final_Alltrails.csv)
The final dataset after data cleaning

**Comment by sachi097** [comment]
Database migration is successful.

Find the code for csv to dynamodb json conversion here.
https://github.com/TrailExplorer/preparations/tree/main/dataset_to_dynamodb_migration

@Anirudhpk2001

**Comment by Anirudhpk2001** [comment]
Closing this issue.
